FF_CONFIGURE="--enable-version3"
FF_CFLAGS="-static-libgcc -static-libstdc++"
FF_CXXFLAGS="-static-libgcc -static-libstdc++"
FF_LDFLAGS="-static-libgcc -static-libstdc++ -mconsole"
GIT_BRANCH="release/4.2"
